// <auto-generated />
using System;
using AECPulse.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AECPulse.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420113757_FixedSeedData")]
    partial class FixedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AECPulse.Domain.Entities.ConversationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("UserIdentity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConversationLogs");
                });

            modelBuilder.Entity("AECPulse.Domain.Entities.FinancialTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4625b87-8d34-450a-9d22-1d54e4f7e27e"),
                            Amount = 50000.00m,
                            CreatedAt = new DateTime(2026, 4, 20, 11, 37, 54, 481, DateTimeKind.Utc).AddTicks(1954),
                            Description = "Concrete Foundation Materials",
                            ProjectId = new Guid("8db7a195-25e6-4927-8025-f938b8e0e7a1"),
                            TransactionDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        });
                });

            modelBuilder.Entity("AECPulse.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LaborBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SpentToDate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8db7a195-25e6-4927-8025-f938b8e0e7a1"),
                            CreatedAt = new DateTime(2026, 4, 20, 11, 37, 54, 479, DateTimeKind.Utc).AddTicks(7202),
                            LaborBudget = 0m,
                            Name = "Skyline Tower Expansion",
                            ProjectNumber = "AEC-2024-001",
                            SpentToDate = 450000.00m,
                            Status = 0,
                            TotalBudget = 1250000.00m
                        },
                        new
                        {
                            Id = new Guid("2d5e865a-9310-4828-9717-3f338d38827c"),
                            CreatedAt = new DateTime(2026, 4, 20, 11, 37, 54, 480, DateTimeKind.Utc).AddTicks(1283),
                            LaborBudget = 0m,
                            Name = "Green Energy Bridge",
                            ProjectNumber = "AEC-2024-002",
                            SpentToDate = 0.00m,
                            Status = 1,
                            TotalBudget = 850000.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
